---
# file: broken.yaml

- hosts: ucspe
  roles:
    - role: admin
    - role: san
  tasks:
  - name: Create SAN Connectivity Policies with Loops
    ucs_san_connectivity:
      name: "{{ san_conn_policy.name }}"
      descr: "{{ san_conn_policy.descr }}"
      wwnn_pool: "{{ san_conn_policy.wwnn_pool }}"
      vhba_list:
        - name: "{{ item.name }}"
          vhba_template: "{{ item.template }}"
          adapter_policy: "{{ item.policy }}"
          order: "{{ item.order }}"
      org_dn: "{{ this_ucs_org }}"
      hostname: "{{ this_ucs_hostname }}"
      username: "{{ this_ucs_username }}"
      password: "{{ this_ucs_password }}"
    loop: "{{ demo_san_conn }}"
