---
# file: cleanup.yaml

- hosts: ucspe
  tasks:
  - name: Remove Demo Sub Organization
    ucs_org:
      org_name: "{{ this_ucs_org_name }}"
      parent_org_path: "{{ this_ucs_org_root }}"
      state: absent
      hostname: "{{ this_ucs_hostname }}"
      username: "{{ this_ucs_username }}"
      password: "{{ this_ucs_password }}"
  - name: Remove VMM VSANs (A/B)
    ucs_vsans:
      name: "{{ item.name }}"
      vsan_id: "{{ item.vsan_id }}"
      vlan_id: "{{ item.vlan_id }}"
      fabric: "{{ item.fabric }}"
      fc_zoning: "{{ item.fc_zoning }}"
      state: absent
      hostname: "{{ this_ucs_hostname }}"
      username: "{{ this_ucs_username }}"
      password: "{{ this_ucs_password }}"
    loop: "{{ demo_vsans }}"
